### ISSUE TITLE
Add logic to dependsOn to check if application is ready

### ISSUE THREAD

**Issue by HenryNguyen5** [erikengervall/dockest#127]
**Is your feature request related to a problem? Please describe.**
A problem I often run into is when I need to start a service like Postgres, and make sure it's ready before a start a main application. The main application does not tolerate the postgres connection not existing initially, so it will crash if postgres is not up. Docker-compose's `depends_on` does not solve this, since it only controls startup order.

**Describe the solution you'd like**
Either: 
- Be able to supply a custom asynchronous hook as a parameter to a runner, which will either resolve (the service is ready) or reject (the service has failed to start)
- Run one of the healthchecks/responsiveness checks and make sure they pass before proceeding with running the services dependent on the current service that is running

**Describe alternatives you've considered**
This is what we use right now to make sure our Postgres service is ready: https://github.com/smartcontractkit/chainlink/blob/develop/tools/docker/wait-for-postgres.sh
What we do is run a `docker-compose -f docker-compose.deps.yaml up` which brings up our test dependencies (the postgres database), wait for that to exit, then run `docker-compose -f docker-compose.integration up` which brings up the rest of the services along with the integration tests.

**Comment by erikengervall** [comment]
Hey, thanks for the feature suggestion!

Just came back from vacations so will have to think about this one for a bit :)

### Initial thoughts

> Note that these alternatives and their code examples are based on current master (i.e 2.x.x alpha) that'll be the next major release soon™️.

The implementation for this feature would probably end up [here](https://github.com/erikengervall/dockest/blob/master/packages/dockest/src/run/waitForServices/index.ts#L30), the part which waits for runners to be ready.

#### Alternative 1

One could assign priorities or weights to runners to decide which should run first, that way one wouldn't have to specify exactly which runner a runner is dependent on.

Using this [example](https://github.com/erikengervall/dockest/blob/master/packages/examples/node-to-node/dockest.ts#L10) the usage would look like

```
run([
  {
    serviceName: 'node_to_node_users',
  },
  {
    serviceName: 'node_to_node_orders',
    weight: '10'
  },
])
```

The higher priority/weight, the earlier it'll run. If omitted, defaults to 1 or something. If no priority/weight is given, no special ordering will be applied.

#### Alternative 2

Extend the runner interface to include dependsOn, thus creating a dockest version of the dependsOn, separate from the docker-compose one.

```
run([
  {
    serviceName: 'node_to_node_users',
  },
  {
    serviceName: 'node_to_node_orders',
    dependsOn: 'node_to_node_users'
  },
])
```

**Comment by HenryNguyen5** [comment]
Sounds great, a potential modification for Alternative would be the following:
```ts
run([
  {
    serviceName: 'node_to_node_users',
  },
  {
    serviceName: 'node_to_node_orders',
    dependsOn: ['{ name: 'node_to_node_users', check: async () => { fetch('http://node_to_node_users/check' }  }']
  },
])

```

**Comment by erikengervall** [comment]
> Sounds great, a potential modification for Alternative would be the following:
> 
> ```ts
> run([
>   {
>     serviceName: 'node_to_node_users',
>   },
>   {
>     serviceName: 'node_to_node_orders',
>     dependsOn: [
>       {
>         name: 'node_to_node_users',
>         check: async () => {
>           await fetch('http://node_to_node_users/check')
>         },
>       },
>     ],
>   },
> ])
> ```

Ideally that `check` function would be a healthcheck for `node_to_node_users` and would always run before `node_to_node_orders` due to the `dependsOn` property:

```
run([
  {
    serviceName: 'node_to_node_users',
    healthchecks: [async () => await fetch(...)]
  },
  {
    serviceName: 'node_to_node_orders',
    dependsOn: ['node_to_node_users']
  },
])
```

Does that cover everything or is there another reason for having a `check` for the `dependsOn`? 🙂 Want to make the interface as easily comprehensible as possible.

**Comment by HenryNguyen5** [comment]
Ah yeah, binding the check to the service itself is a lot more intuitive. Do we need to have the healthCheck be multiple though? I'd imagine just one function is fine. So the property would be `healthcheck`

**Comment by erikengervall** [comment]
> Ah yeah, binding the check to the service itself is a lot more intuitive. Do we need to have the healthCheck be multiple though? I'd imagine just one function is fine. So the property would be `healthcheck`

Yeah, the thought has actually crossed my mind 😄 

I ended up allowing multiple healthchecks because I wanted to expose some default healthchecks for some common services and rather than including those healthchecks within a healthcheck, one would simply add it to the list. Perhaps "nesting" the default healthcheck provided by the library within ones own healthcheck isn't a bother in which case I probably should reconsider 🙂 

Some pseudo-code examples

### Single healthcheck

```
import { defaultNodeHealthcheck } from 'dockest'

run([
  {
    serviceName: 'node_to_node_users',
    healthcheck: async () => {
      await defaultNodeHealthcheck(...)
      await fetch(...)
    }
  }
]
```

### Multiple healthchecks

```
import { defaultNodeHealthcheck } from 'dockest'

run([
  {
    serviceName: 'node_to_node_users',
    healthchecks: [async () => await fetch(...), defaultNodeHealthcheck]
  }
]
```

Please give your thoughts on this!

**Comment by HenryNguyen5** [comment]
The first one is definitely more simple. The second version does give the ability to tell the user which typecheck failed by index, if you care for supporting that. If you don't need to (I personally don't think it's a big plus to know which check failed, you can simply add logging :)) then I think the first option is simpler.

Another alternative you can consider for the first option is to compose the default healthcheck like so:

```ts
import { defaultNodeHealthcheck, defaultNodeHealthcheckWith } from 'dockest'

run([
  {
    serviceName: 'node_to_node_users',
    healthcheck: defaultNodeHealthcheck({} /* opts */)
  }
]

// but if we want with another additional check...
run([
  {
    serviceName: 'node_to_node_users',
    healthcheck: defaultNodeHealthcheckWith({} /* opts */, async () => {
		await anotherCheck()
	})
  }
]

```
I think I prefer the first option, just wanted to add the composable option to put it out there.

**Comment by erikengervall** [comment]
> The first one is definitely more simple. The second version does give the ability to tell the user which typecheck failed by index, if you care for supporting that. If you don't need to (I personally don't think it's a big plus to know which check failed, you can simply add logging :)) then I think the first option is simpler.
> 
> Another alternative you can consider for the first option is to compose the default healthcheck like so:
> 
> ```ts
> import { defaultNodeHealthcheck, defaultNodeHealthcheckWith } from 'dockest'
> 
> run([
>   {
>     serviceName: 'node_to_node_users',
>     healthcheck: defaultNodeHealthcheck({} /* opts */)
>   }
> ]
> 
> // but if we want with another additional check...
> run([
>   {
>     serviceName: 'node_to_node_users',
>     healthcheck: defaultNodeHealthcheckWith({} /* opts */, async () => {
> 		await anotherCheck()
> 	})
>   }
> ]
> ```
> 
> I think I prefer the first option, just wanted to add the composable option to put it out there.

Thanks for the feedback! I'll definitely consider going with a single healthcheck and leave it up to the user to build/compose it as they wish 🙂

**Comment by HenryNguyen5** [comment]
Awesome, thank you!

Don't have too much bandwidth now, but if I free up I'll let you know on this issue
