### ISSUE TITLE
Set jest as a peer dependency

### ISSUE THREAD

**Issue by HenryNguyen5** [erikengervall/dockest#147]
**Is your feature request related to a problem? Please describe.**
Setting jest as a peer dependency would make it so that consumers dont install breaking versions of jest that this library does not account for.

**Comment by erikengervall** [comment]
> **Is your feature request related to a problem? Please describe.**
> Setting jest as a peer dependency would make it so that consumers dont install breaking versions of jest that this library does not account for.

That'd be awesome! I'm not sure exactly how to go about it whilst maintaining the ability to run unit tests towards the library itself (i.e. `packages/dockest`). Do you have any suggestions?
