### ISSUE TITLE
setup github action that publishes nightly releases from master (or pull requests) to npm

### ISSUE THREAD

**Issue by n1ru4l** [erikengervall/dockest#153]
This would make testing new features in your own application much easier.

Example: https://github.com/dotansimha/graphql-code-generator/blob/677ff5647eecf4c7913f8e8780bbd0ff128f28c0/.github/workflows/main.yml#L54-L75

**Comment by erikengervall** [comment]
> This would make testing new features in your own application much easier.
> 
> Example: https://github.com/dotansimha/graphql-code-generator/blob/677ff5647eecf4c7913f8e8780bbd0ff128f28c0/.github/workflows/main.yml#L54-L75

Good idea!

I'll experiment with the concept in my playground repo :+1:

**Comment by erikengervall** [comment]
#197 validated to fix this issue

https://www.npmjs.com/package/dockest/v/2.1.0-bd3ef6c is the first "next" (also known as canary/pre-release) build to be published 🎉
