### ISSUE TITLE
docker-compose parsing: convert "oldschool" port format to new port format

### ISSUE THREAD

**Issue by n1ru4l** [erikengervall/dockest#155]
extract from: https://github.com/erikengervall/dockest/issues/140

> A Postgres service in docker-compose.yml must use a full ports format with target and published, not something like 5432:5432. If a wrong format is used, the result is connection timeout (healthcheck) without explanation which is bewildering.

We should probably convert the old-school format "port:port" to -> the new format `{ "published": port, "target": port }` , so that the check here does not fail with weird reasons.

https://github.com/erikengervall/dockest/blob/7da1dda02bebd7734c73a186c73aa010a5bc711b/packages/dockest/src/run/waitForServices/checkConnection.ts

I got the same report from a co-worker in Slack:

>  cannot get even the simplest example to work with dockest. The readiness check for redis is timing out although I configured it with the default example and the port 6379 is specified.
[Check Connection] Timeout in 9s (localhost:undefined)

**Comment by n1ru4l** [comment]
I actually thought this would not occur because of https://github.com/erikengervall/dockest/pull/82#issuecomment-533990224

@erikengervall Any ideas which change could have caused a regression?

**Comment by erikengervall** [comment]
> We should probably convert the old-school format "port:port" to -> the new format { "published": port, "target": port } , so that the check here does not fail with weird reasons.

That sounds like a good idea.

> I actually thought this could not occur because of #82 (comment)
> 
> @erikengervall Any ideas which change could have caused a regression?

Hm, odd!

Currently we use 3.7 regardless of the user's version:
https://github.com/erikengervall/dockest/blob/f1bf18fb40828f68559c85fd6804102ba7e8b835/packages/dockest/src/run/bootstrap/getParsedComposeFile.ts#L9-L15

I was under the impression that simply by using version 3.7, the `docker-compose config` would handle short formats and transform it to long formats. Perhaps I was mistaken 😕

**Comment by erikengervall** [comment]
Released in 2.0.1 :)
