### ISSUE TITLE
better docker in docker/docker socket injected into docker support

### ISSUE THREAD

**Issue by n1ru4l** [erikengervall/dockest#159]
**Is your feature request related to a problem? Please describe.**

When implementing the "detect whether tests are executed inside a container" check, I assumed that every use-case assumes, that the docker socket is injected into the test-runner container from the host machine.

The feature was implemented while assuming that all CI solutions behave the same. I used the local aws-codebuild as a reference.

Now I am trying to get Dockest running on the real AWS Codebuild and see that there is quite a big difference:

Instead of injecting the docker socket from the host machine into the container it is actually encouraged to run a new docker daemon inside the docker container (Docker in Docker). Furthermore, there is no possibility to access the socket of the host machine.

This causes dockest to fail the tests for the following reasons:

1. It detects that tests are run inside docker (using [is-docker](https://www.npmjs.com/package/is-docker))
2. It tries to link the container to a new network (but fails, because the container is not available in the local docker daemon scope)
3. It tries to do the connectivity checks on the target ports (but should run them on the published ports)
4. It tries to do the connectivity checks on the internal hostnames (but should run them on localhost)

**Describe the solution you'd like**

We need a better solution for detecting whether

1. The docker socket got injected from the host machine

_or_

2. The docker socket got created by a docker daemon inside the container

**Possible Implementations:**

> It tries to link the container to a new network (but fails, because the container is not available in the local docker daemon scope)

We could assume that if this step fails we are in a Docker in Docker environment, but it could possibly be too flaky and error-prone.

I Will check for other alternatives in the meantime.

**Describe alternatives you've considered**
For now, I patched my version with `patch-package`.

**Comment by oemergenc** [comment]
Hi, thanks for the lib. Actually i am currently running into this. Using dockest for integration testing of my service. While locally everythings is working as expected, i am having trouble on my ci server. I am running jenkins as docker image in the cloud and while executing dockest tests inside of jenkins, the test fails with a error message like the following:

```
15:16:47  🌈 Dockest 🌈 [Shell] <docker network ls --filter driver=bridge --filter name=dockest_bridge_network --quiet>
15:16:47  🌈 Dockest 🌈 Using existing network "dockest_bridge_network"
15:16:47  🌈 Dockest 🌈 [Shell] <docker network connect dockest_bridge_network --alias host.dockest-runner.internal 4d677cff0675>
15:16:47  🐥  zookeeper 🐥  [Setup] Initiating...
15:16:47  🌈 Dockest 🌈 [Shell] <docker-compose -f /home/jenkins/workspace/onsumer_feature_fix-docker-setup/docker-compose.dockest-generated.yml up --detach zookeeper>
15:16:50  🐥  zookeeper 🐥  Still waiting for start event... Timeout in 30s
15:16:51  🐥  zookeeper 🐥  Still waiting for start event... Timeout in 29s
15:16:52  🐥  zookeeper 🐥  Still waiting for start event... Timeout in 28s
15:16:52  🐥  zookeeper 🐥  Still waiting for start event... Timeout in 27s
15:16:53  🐥  zookeeper 🐥  Still waiting for start event... Timeout in 26s
```

Any ideas on how to work around this currently?

**Comment by n1ru4l** [comment]
We are still stuck with version 1 since I need to backport all changes of my v1 fork back to v2 :D

I basically overwrote the `isDocker()` calls with `false` using patch-package.

```diff
diff --git a/node_modules/dockest/dist/index.js b/node_modules/dockest/dist/index.js
index 6a76b09..373623f 100644
--- a/node_modules/dockest/dist/index.js
+++ b/node_modules/dockest/dist/index.js
@@ -30,7 +30,7 @@ class Dockest {
         };
         this.run = async () => {
             this.config.$.perfStart = Date.now();
-            this.config.$.isInsideDockerContainer = is_docker_1.default();
+            this.config.$.isInsideDockerContainer = false;
             if (this.config.$.isInsideDockerContainer) {
                 this.config.runners.forEach(runner => {
                     runner.isBridgeNetworkMode = true;
```

```diff
--- a/node_modules/dockest/dist/test-helper/index.js
+++ b/node_modules/dockest/dist/test-helper/index.js
@@ -4,7 +4,7 @@ var __importDefault = (this && this.__importDefault) || function (mod) {
 };
 Object.defineProperty(exports, "__esModule", { value: true });
 const is_docker_1 = __importDefault(require("is-docker")); // eslint-disable-line import/default
-const isInsideDockerContainer = is_docker_1.default();
+const isInsideDockerContainer = false;
 if (!process.env.DOCKEST_INTERNAL_CONFIG) {
     throw new Error('Not executed inside dockest context.');
 }
```

**Comment by oemergenc** [comment]
Hey, thanks for the. quick feedback. 

I dont know if i understood correctly. I am using version 2.0.1 while running into the described problem. Is there anything i can do right now to workaround this?

**Comment by n1ru4l** [comment]
@oemergenc Actually I am not 100% sure whether this is related to this issue. Is it possible for you to collect the logs of those containers? That could be very insightful, unfortunately there is currently no option for collecting the logs with dockest. You could start the log collection in a new shell after you started dockest with `docker-compose - docker-compose.dockest-generated.yml logs -f > debug.log`

**Comment by oemergenc** [comment]
Nevermind, i was able to solve this. 
The problem was a zombie docker network, after removing it, the build succeeds.

Thank you.

**Comment by n1ru4l** [comment]
@oemergenc if there is something we could do inside dockest in order to make the experience smoother let us know, by opening a new issue with a detailed explanation of your issue ☺️
