### ISSUE TITLE
failed command error message gets swallowed

### ISSUE THREAD

**Issue by n1ru4l** [erikengervall/dockest#75]
**Describe the bug**

When you define a command via the commands option for the `PostgresRunner` and the given command failes the error message is swallowed:

```
🌈 Dockest 🌈 Exithandler invoked from process event unhandledRejection
```

This even occurs with the debug log level.

**Expected behavior**
The error message or the log of the executed command is printed

**Comment by n1ru4l** [comment]
Seems like this got resolved here: https://github.com/erikengervall/dockest/blob/a56338482ff892f7a5170feaf8de8de55adf78a5/src/onInstantiation/setupExitHandler.ts#L25

@erikengervall Can I close this, or is there anything further to improve?

**Comment by erikengervall** [comment]
> @erikengervall Can I close this, or is there anything further to improve?

Yes!

There might yet be some places where errors doesn't find their way to the exitHandler due to their scope being async which causes the exitHandler to receive unhandled promise rejections with an empty reason. But let's create new issues when we encounter these type of cases!
