### ISSUE TITLE
allow containers to connect to the host machine

### ISSUE THREAD

**Issue by n1ru4l** [erikengervall/dockest#79]
In one of my integration tests, I am starting a webserver (via jest) and check whether a webhook on that webserver is called by a service in a docker container.

There are several options for this: https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach

It would be awesome if this could be easily achieved with this library!

**Edit:**

Some more thoughts:

On platforms like AWS Codebuild, the code is already built inside a container. For starting additional containers the docker socket is injected into the container. That means if you start a new container and want it to be able to connect to the main "test" container you will have to set up a network between those containers.

**Comment by erikengervall** [comment]
> Need to find out whether `dockest` is run inside a docker container or not.

Initially this responsibility could be placed on the user (i.e. via configuration) until a reliable solution is found.

> In case it is run inside a container we have to create a network for linking all runner containers to the dockest container.

Hm, is it safe to assume that all projects wants all services to be linked to one another? The default mode could definitely hook everything up to each other and down the line an option could be introduced where the networking can be managed more granularly.

> It would then also be helpful to add runtime helper that allows resolving the hostname of a given service at runtime.

Yeah definitely. If it's possible to globalize this type of information I'd be thrilled!

**Comment by n1ru4l** [comment]
> Initially this responsibility could be placed on the user (i.e. via configuration) until a reliable solution is found.

[`is-docker`](https://github.com/sindresorhus/is-docker#readme) seems like a widely used solution (almost 700,000 weekly downloads). Of course, we could still allow overwriting this (dunno about other peoples setup).

> Hm, is it safe to assume that all projects wants all services to be linked to one another? The default mode could definitely hook everything up to each other and down the line an option could be introduced where the networking can be managed more granularly.

We could either go that route or generate a network for each pair (dockest container and service container). I agree for keeping it simple and add a more granular configuration option in the future.

> Yeah definitely. If it's possible to globalize this type of information I'd be thrilled!

I will do some research!

**Comment by erikengervall** [comment]
> is-docker seems like a widely used solution (almost 700,000 weekly downloads). Of course, we could still allow overwriting this (dunno about other peoples setup).

Looks like a solid library, could definitely use it in the first iteration of this feature.

> I will do some research!

Awesome, thanks!

**Comment by n1ru4l** [comment]
There is no simple way for doing this.

https://github.com/facebook/jest/issues/7184

We could, however, export a module from "dockest" that could be used for doing such stuff. It could be an abstraction above the `docker` and/or `docker-compose` cli for retrieving info such s the hostname etc.

example api:

```tsx
import { getServiceHost } from "dockest/jest"

test("my test", async () => {
  const host = await getServiceHost("website")
})
```

The remaining problem would be the following: how does the `dockest/jest` know the used services? It would need to somehow parse the `docker-compose.dockest-generated.yml` file.

____

**Alternative approach:**

Give the containers that you connect to the container an alias that is equivalent to the one in the `docker-compose.dockest-generated.yml` file. That way we do not need a jest helper library. Users just have to follow the convention of using the docker-compose url like they would actually also do in your application code (assuming they use docker-swarm or docker-compose in production). So this might be the better way (at least for now)?

```tsx
import Dockest, { runners, logLevel } from "dockest";

const runner = new runners.GeneralPurposeRunner({
  service: "website",
  build: "./app",
  ports: {
    "9000": "9000"
  },
  responsivenessTimeout: 30 * 1000,
  connectionTimeout: 30 * 1000,
  // return continerId as host
  host: containerId => containerId
});

const dockest = new Dockest({
  opts: {
    logLevel: logLevel.DEBUG
  }
});

dockest.attachRunners([runner]);

dockest.run();
```

```bash
docker network connect dockest_bridge_network --alias website service-host
```

**Comment by n1ru4l** [comment]
I got a first docker-in-docker solution working over here: https://github.com/n1ru4l/dockest/pull/1. Will create a pull request over here once my other ones are merged.

The dockest in docker approach is working fine!

However, there are some complications with connecting to the host machine. On Mac OSX and windows, you can reach the docker host trough the hostname `host.docker.internal`. On Linux, there is no official way (https://github.com/docker/for-linux/issues/264).

However, there are various hacks available, the easiest seemed to be the following:

**check whether `process.env` is `linux` and manually add the hostname to `/etc/hosts`**

```tsx
if (process.platform === 'linux' && !runner.isBridgeNetworkMode) {
    const command = ` \
      docker exec ${runner.containerId} \
        /bin/sh -c "ip -4 route list match 0/0 | awk '{print \\$3\\" host.docker.internal\\"}' >> /etc/hosts"
    `
    await execa(command)
  }
```

The next issue I have is that ideally, I want to run `yarn test` without having to write some custom logic for checking whether I have to connect to `host.docker.internal` (dockest on host machine mode) or a container id (dockest inside docker container mode). Which is only solvable by providing test runtime helpers (https://github.com/n1ru4l/dockest/pull/1/commits/fdce24407ed92a0a8c1e86916b9023dffe2ac6b5#diff-de61c684d5eed40fdbba538134d5258f).

We can share the docker-compose config with the test specs by setting them to `process.env` as a string. `jest.runCLI` will then forward the environment variable to the workers that run the tests.
