### ISSUE TITLE
make package json scripts more non-bash user friendly

### ISSUE THREAD

**Issue by n1ru4l** [erikengervall/dockest#87]
- [x] stuff like `rm -rf` and the bash scripts are not available on windows. `rm -rf` can be replaced with [`rimraf`](https://www.npmjs.com/package/rimraf)
- [x] Git hooks could be replaced with [`husky`](https://github.com/typicode/husky).
- [x] [`lint-staged` ](https://github.com/okonet/lint-staged) can be used for running eslint upon committing files.
- [x] Instead of using bash scripts for installing all examples/running tests we could use yarn workspaces together with lerna ([example](https://github.com/dotansimha/graphql-code-generator/blob/master/package.json)).

**Comment by erikengervall** [comment]
Yes, yes and yes!

**Comment by erikengervall** [comment]
> * [x]  stuff like `rm -rf` and the bash scripts are not available on windows. `rm -rf` can be replaced with [`rimraf`](https://www.npmjs.com/package/rimraf)
> * [x]  Git hooks could be replaced with [`husky`](https://github.com/typicode/husky).
> * [x]  [`lint-staged` ](https://github.com/okonet/lint-staged) can be used for running eslint upon committing files.
> * [x]  Instead of using bash scripts for installing all examples/running tests we could use yarn workspaces together with lerna ([example](https://github.com/dotansimha/graphql-code-generator/blob/master/package.json)).

All of the above have been implemented!
